# 对等节点配置
# 如果使用此文件，将覆盖默认的 peer 配置

[[peer]]
uri = "tcp://public.easytier.cn:11010"

[[peer]]
uri = "tcp://et.gbc.moe:11010"

[[peer]]
uri = "tcp://et.gbc.moe:11010"

[[peer]]
uri = "tcp://weior.top:11010"

[[peer]]
uri = "tcp://221.7.223.136:11010"

[[peer]]
uri = "tcp://gz.server.piedaochuan.top:11010"
# 可以添加更多 peer
# [[peer]]
# uri = "tcp://your-peer-ip:19001"
